package CourseRegistrationSystem;


/**
* CourseRegistrationSystem/CourseData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from app.idl
* Thursday, November 1, 2018 at 9:02:28 PM Eastern Daylight Time
*/

public interface Course extends CourseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CourseData
