package CourseRegistrationSystem;


/**
* CourseRegistrationSystem/Course.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from app.idl
* Sunday, November 4, 2018 at 1:51:40 PM Eastern Standard Time
*/

public interface Course extends CourseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Course
