package CourseRegistrationSystem;


/**
* CourseRegistrationSystem/CourseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from app.idl
* Thursday, November 1, 2018 at 9:02:28 PM Eastern Daylight Time
*/

public interface CourseOperations 
{
  boolean validateAdvisor (String clientId);
  boolean validateStudent (String clientId);
  boolean addCourse (String id, String courseId, String courseName, String term, short seatsAvailable);
  void showCourses ();
  boolean deleteCourse (String id, String courseId, String term, String department);
  String enrollCourse (String id, String term, String department, boolean udpCall);
  String displayCourses (String term);
  boolean dropCourse (String studentId, String courseId, String term, String department, boolean udpCall);
  String getClassSchedule (String studentId);
  String listCourseAvailability (String id, String term, String department, boolean udpCall);
} // interface CourseOperations
